### ISSUE TITLE
list of FreshOranges empty because only Day7 has data >0

### ISSUE THREAD

**Issue by Archaeopteryx** [klahnakoski/FreshOranges#5]
https://charts.mozilla.org/FreshOranges/index.html shows no data. Inspection of `response.data` shows only `Day7` has data >0.

https://charts.mozilla.org/NeglectedOranges/index.html is also empty but the 10 bugs in its reponse had a comment in the last week. It might be correct.

**Comment by klahnakoski** [comment]
Yes, the bzETL is broken https://bugzilla.mozilla.org/show_bug.cgi?id=1595686

So is the TreeherderETL https://bugzilla.mozilla.org/show_bug.cgi?id=1594715
