### ISSUE TITLE
list of fresh oranges is empty

### ISSUE THREAD

**Issue by AndreeaPavel** [klahnakoski/FreshOranges#6]
Haven't seen any data in https://charts.mozilla.org/FreshOranges/index.html and was wondering why bug 1612233 didn't show up in the last week. 
Aryx mentioned that the condition is if (b.Day2 >= MIN_ORANGE_COUNT && (b.Day2 == b.Day14 || b.Day3 == b.Day7)) {
MIN_ORANGE_COUNT is 10

day2 = 8, day3 = 14,  day7 = 32, day14 = 0

is day 14 = 0 a bug?

**Comment by klahnakoski** [comment]
This looks fine.  the 2day count did not go above 10.  `day14 = 0` means there are no  oranges between 1 and 2 weeks ago. This bug is staying below the threshold.

**Comment by AndreeaPavel** [comment]
huh, seems weird there were none. thank you for checking, I will close this then.
